tasks:
  - init: |
      sudo docker pull registry.jetbrains.team/p/prj/containers/projector-idea-u
    command: |
      sudo mkdir -p .jetbrains; sudo touch .jetbrains/.gitkeep; sudo chown -R 1000:1000 .jetbrains
      
      sudo docker run --rm -p 8887:8887 -v $(pwd)/.jetbrains:$(pwd) -it registry.jetbrains.team/p/prj/containers/projector-idea-u
ports:
  - port: 8887
    visibility: private
    onOpen: open-browser
